#!/bin/bash

#
# Copyright (C) 2025 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

# If the control reaches this step, the service can be enabled and started

# Ensure all environment files exist
touch ldap.env
touch smarthost.env
touch config.env

source config.env

# Enable Matrix services
systemctl --user enable postgresql.service
systemctl --user enable synapse.service

# Enable element web client when enabled in UI
if [[ -n ${ELEMENT_DOMAIN_NAME} ]]; then
  systemctl --user enable element-web.service
else
  systemctl --user disable element-web.service
fi

# Enable cinny client when enabled in UI
if [[ -n ${CINNY_DOMAIN_NAME} ]]; then
  systemctl --user enable cinny.service
else
  systemctl --user disable cinny.service
fi

systemctl --user enable matrix.service

# Restart Matrix services
systemctl --user restart postgresql.service
systemctl --user restart synapse.service

# Restart element web client when enabled in UI, else stop it
if [[ -n ${ELEMENT_DOMAIN_NAME} ]]; then
  systemctl --user restart element-web.service
else
  systemctl --user stop element-web.service
fi

# Restart cinny client when enabled in UI, else stop it
if [[ -n ${CINNY_DOMAIN_NAME} ]]; then
  systemctl --user restart cinny.service
else
  systemctl --user stop cinny.service
fi

# Manage matrix2acrobits service
if [[ -n ${NETHVOICE_AUTH_URL} ]]; then
  # Enable NethVoice Matrix Auth service
  systemctl --user enable matrix2acrobits.service
  # Restart NethVoice Matrix Auth service
  systemctl --user restart matrix2acrobits.service
else
  # Disable and stop NethVoice Matrix Auth service
  systemctl --user disable --now matrix2acrobits.service
fi