#!/usr/bin/env python3

#
# Copyright (C) 2023 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import sys
import json
import agent
import os

#request = json.load(sys.stdin)
#renv = request['config.env']

# Read current configuration
if os.path.exists("config.env"):
    env_vars = agent.read_envfile("config.env")
else:
    env_vars = {}

configure_retval = agent.tasks.run(agent_id=os.environ['AGENT_ID'], action='configure-module', data=env_vars)
agent.assert_exp(configure_retval['exit_code'] == 0, "The configure-module subtask failed!")
